apiVersion: v1
kind: Pod
metadata:
  name: test-node-affinity-preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: slow-node
                operator: In
                values:
                  - "true"
  containers:
    - name: nginx
      image: nginx
