apiVersion: v1
kind: Pod
metadata:
  name: test-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: non-existent-label
                operator: In
                values:
                  - "true"
  containers:
    - name: nginx
      image: nginx
