apiVersion: v1
kind: Pod
metadata:
  name: test-node-affinity-cordoned
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: In
                values:
                  - "restricted"
  containers:
    - name: nginx
      image: nginx
